CREATE DATABASE chat;

USE chat;

CREATE TABLE person
(
(id INT AUTO_INCREMENT NOT NULL PRIMARY KEY),
(name VARCHAT(25) NOT NULL)
);

CREATE TABLE message
(
(id INT AUTO_INCREMENT PRIMARY KEY),
(createdDate TIMESTAMP NOT NULL),
()
);